---
title: "Untitled"
author: "Flavio"
date: "13 11 2020"
output: html_document
runtime: shiny
---

# **Information about Beer around the world**

  
<br>

### Using data from 2015 about Beerprices and Beer consumption (data from  goeurop now omio.de) to bild a small shinyapp with RMarkdown (codes and data on GitHub: https://github.com/fvr1210/beer_prices)
<br>
 

```{r packages, include=FALSE}
library(tidyverse) # Version 1.3.0
library(shiny) # Version 4.0.3
library(lubridate)

```

```{r daten, include=FALSE}
df_b <- read_delim("../processed-data/wwbp_with_countries_continents_regions.csv", delim = ";" , locale = locale(encoding = 'ISO-8859-2'))


```

```{r city, echo=F}




checkboxGroupInput(inputId = "d_cc",label = "City:", inline = T,
                                                    choices = sort(unique(df_b$cc)),
                                                    selected = sort(unique(df_b$cc)))


checkboxGroupInput(inputId = "d_region", label = "Regions:", inline = T,
                                                    choices = sort(unique(df_b$region)),
                                                    selected = sort(unique(df_b$region)))
```

```{r city_data_reaktiv, echo=F}
# filtering the reactive datasets based on the choices made
df_bC <- reactive({
  filter(df_b, cc %in% input$d_cc & region %in% input$d_region)
})

```

```{r plot city, echo=F}
 renderPlot ({
  
   ggplot(df_bC(), aes(x=reorder(cc, -`BAR PRICE $`), y = `BAR PRICE $`, fill = region)) +
   geom_bar(stat="identity", position = position_dodge(width=0.9), width = 0.85, color = NA) +
   # scale_fill_manual(values = col_age) +
   scale_x_discrete() +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_fill_brewer(palette = "Dark2")
 })

```






```{r country or region, echo=F}




radioButtons("VarA",label = "Choose a geographical scale:", inline = T,
                    choices = c('Countries', 'Regions'),
                    selected='Countries')


conditionalPanel(
  condition = "input.VarA == 'Countries'",
  checkboxGroupInput(inputId = "d_country", label = "Countries:", inline = T,
                                                    choices = sort(unique(df_b$country)),
                                                    selected = sort(unique(df_b$country)))
)

conditionalPanel(
  condition = "input.VarA == 'Regions'",
  checkboxGroupInput(inputId = "d_region_2",label = "Regions:", inline = T,
                                                    choices = sort(unique(df_b$region)),
                                                    selected = sort(unique(df_b$region))))
```

```{r country_region_data_reaktiv, echo=F}
# filtering the reactive datasets based on the choices made
df_bc <- reactive({
   filter(df_b, country %in% input$d_country)
 }) 


df_br <- reactive({
   filter(df_b, region %in% input$d_region2)
 }) 

```
```{r plot country_region, echo=F}
 renderPlot ({
#Countries as variable
  if (input$VarA=="Countries"){   
   ggplot(df_bc(), aes(x=CITY, y = `BAR PRICE $`, fill = region)) +
   geom_bar(stat="identity", position = position_dodge(width=0.9), width = 0.85, color = NA) +
   # scale_fill_manual(values = col_age) +
   scale_x_discrete() +
  theme_bw() 
  }  
#Falls Geschecht ausgewählt
  else {   
     ggplot(df_br(), aes(x=CITY, y = `BAR PRICE $`, fill = region)) +
   geom_bar(stat="identity", position = position_dodge(width=0.9), width = 0.85, color = NA) +
   # scale_fill_manual(values = col_age) +
   scale_x_discrete() +
  theme_bw() 
  }  
 })


```
